### PR TITLE
Add cli usage section in readme

### PR DESCRIPTION
**Pull request by kootoopas**

### CODE REVIEW

**Comment by kootoopas** [comment]
Well, that ain't gonna work. 🙃🏳️

**Comment by tomas** [comment]
Why not?

**Comment by kootoopas** [comment]
Was open for 1.5 months wo/ any response so I thought it wasn't going anywhere. Reopening rn. 🙂

**Comment by tomas** [comment]
Oh that's just me, nothing wrong with the PR. :)

**Pull request merged**
